apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jumping-monster
  name: jumping-monster
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jumping-monster
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jumping-monster
    spec:
      containers:
      - image: #{REGISTRY_URL}#/#{IMAGE_NAME}#:#{BUILD_ID}#
        imagePullPolicy: IfNotPresent
        name: jumping-monster
      imagePullSecrets:
      - name: docker-secret
