apiVersion: v1
kind: Service
metadata:
  labels:
    app: jumping-monster
  name: jumping-monster
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: jumping-monster
  type: LoadBalancer

